import React from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          {/* Header */}
          <header className="text-white p-4">
            <nav className="container mx-auto flex justify-around items-center">
              <h1 className="text-2xl font-bold">
                Meu<a className="text-blue-500">Portfólio</a>
              </h1>
              <ul className="flex space-x-4">
                <li>
                  <Link href="#projetos" className="hover:text-blue-500">
                    Projetos
                  </Link>
                </li>
                <li>
                  <Link href="#habilidades" className="hover:text-blue-500">
                    Habilidades
                  </Link>
                </li>
                <li>
                  <Link href="#curriculo" className="hover:text-blue-500">
                    Curriculo
                  </Link>
                </li>
                <li>
                  <Link href="#contato" className="hover:text-blue-500">
                    Contato
                  </Link>
                </li>
              </ul>
            </nav>
          </header>

          {/* Main Content */}
          <main className="flex-grow container mx-auto p-4">{children}</main>

          {/* Footer */}
          <footer className="bg-blue-500 text-white text-center p-2">
            <p>© 2024 Niceu Biriba. Todos os direitos reservados.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
